=== hypernumbernet/conecmo/xml/form.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT form (fieldMargin|color|font|fields)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fieldMargin (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT color (fore|back)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fore (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT back (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT font (family|size)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT family (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT size (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fields (lineEdit)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT lineEdit (position|display|width|align|tooltip|label|css|top|left)*>
<!ATTLIST lineEdit
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT position (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT display (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT width (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT align (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tooltip (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT label (position|width|text|rightText|top|left)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT text (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT rightText EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT css (style|class|hoverClass)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT style EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT class EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hoverClass EMPTY>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT top (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT left (#PCDATA)>

=== hypernumbernet/conecmo/user/form#sample.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE form SYSTEM '../xml/form.dtd'>

<form>
    <width>800</width>
    <height>500</height>
    <fieldMargin>5</fieldMargin>
    <color>
        <fore>black</fore>
        <back>#ddd</back>
    </color>
    <font>
        <family>sans-serif</family>
        <size>15</size>
    </font>
    <script></script>
    <fields>
        <field id="i001" type="text">
            <position>static</position>
            <float>left</float>
            <width>200</width>
            <align>left</align>
            <tooltip>Tips</tooltip>
            <label>
                <width>140</width>
                <text>フィールド01:</text>
            </label>
            <rightLabel>
                <width>140</width>
                <text>F01右</text>
            </rightLabel>
            <css>
                <style></style>
                <class></class>
                <hoverClass></hoverClass>
            </css>
        </field>
        <field id="i002" type="text">
            <width>100</width>
            <label>
                <text>フィールド02:</text>
            </label>
        </field>
        <field id="i003" type="text">
        </field>
        <field id="id" type="text">
            <position>absolute</position>
            <width>200</width>
            <top>100</top>
            <left>400</left>
            <tooltip>absolute field</tooltip>
            <label>
                <text>id: </text>
                <width>50</width>
                <top>100</top>
                <left>350</left>
            </label>
        </field>
    </fields>
</form>
